name: Publish package to GitHub Packages
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@joshuaalpuerto'
      - run: npm build
      
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
